[project]
name = "disasters-server"
version = "0.1.0"
description = "ALL NATURAL DISASTERS 1900-2021 / EOSDIS from kagglehub"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [ "mcp>=1.27.0",]
[[project.authors]]
name = "Ramiro Andrés Bedoya E."
email = "iamramiroo@gmail.com"

[build-system]
requires = [ "uv_build>=0.11.8,<0.12.0",]
build-backend = "uv_build"

[project.scripts]
disasters-server = "disasters_server:main"
